# Generated by Django 3.0.4 on 2020-03-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanput_id', models.IntegerField(blank=True, default='')),
                ('port', models.IntegerField(blank=True, default='')),
                ('banner', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Scanput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('ip', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('wappalyzer', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dic', models.IntegerField(blank=True, default='')),
                ('censys_id', models.CharField(blank=True, default='', max_length=50)),
                ('censys_secret', models.CharField(blank=True, default='', max_length=50)),
                ('dnsdb_id', models.CharField(blank=True, default='', max_length=50)),
                ('dnsdb_secret', models.CharField(blank=True, default='', max_length=50)),
                ('shodan_api', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('tool_google', models.BooleanField(default=False)),
                ('tool_blast', models.BooleanField(default=False)),
                ('tool_censys', models.BooleanField(default=False)),
                ('tool_dnsdb', models.BooleanField(default=False)),
                ('tool_shodan', models.BooleanField(default=False)),
                ('namp', models.BooleanField(default=False)),
                ('wappalyzer', models.BooleanField(default=False)),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
