# Generated by Django 3.0.4 on 2020-03-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='namp',
            new_name='nmap',
        ),
    ]
